#!/bin/sh

# Instructions:
# Put this file into your .git/hooks folder and set as executable
#   - for Windows (attrib +x pre-commit)
#   - for *nix (chmod +x pre-commit)

# echo "Starting the server"
# npm run start:dev

echo "Running unit tests:"
echo "  Do not forget to start the server before with 'npm run start:dev'."
# npm run start:email &
# npm test

# Do not abort the commit because of errors
exit 0
