mongoimport --db evse --collection companies --file export/companies.json
mongoimport --db evse --collection companylogos --file export/companylogos.json
mongoimport --db evse --collection sites --file export/sites.json
mongoimport --db evse --collection siteimages --file export/siteimages.json
mongoimport --db evse --collection siteareas --file export/siteareas.json
mongoimport --db evse --collection siteareaimages --file export/siteareaimages.json
mongoimport --db evse --collection authorizes --file export/authorizes.json
mongoimport --db evse --collection bootnotifications --file export/bootnotifications.json
mongoimport --db evse --collection chargingstations --file export/chargingstations.json
mongoimport --db evse --collection configurations --file export/configurations.json
mongoimport --db evse --collection datatransfers --file export/datatransfers.json
mongoimport --db evse --collection metervalues --file export/metervalues.json
mongoimport --db evse --collection migrations --file export/migrations.json
mongoimport --db evse --collection eulas --file export/eulas.json
mongoimport --db evse --collection notifications --file export/notifications.json
mongoimport --db evse --collection pricings --file export/pricings.json
mongoimport --db evse --collection statusnotifications --file export/statusnotifications.json
mongoimport --db evse --collection tags --file export/tags.json
mongoimport --db evse --collection transactions --file export/transactions.json
mongoimport --db evse --collection users --file export/users.json
mongoimport --db evse --collection userimages --file export/userimages.json
