require('source-map-support').install();

module.exports = {
	// Statuses
	NOTIF_ENTITY_SITE: "Site",
	NOTIF_ENTITY_SITE_AREA: "SiteArea",
	NOTIF_ENTITY_COMPANY: "Company",
	NOTIF_ENTITY_CHARGING_STATION: "ChargingStation",
	NOTIF_ENTITY_CHARGING_STATION_STATUS: "Status",
	NOTIF_ENTITY_CHARGING_STATION_CONFIG: "Configuration",
	NOTIF_ENTITY_TRANSACTION: "Transaction",
	NOTIF_ENTITY_TRANSACTION_STOP: "Stop",
	NOTIF_ENTITY_TRANSACTION_METER_VALUES: "MeterValues",
	NOTIF_ENTITY_USER: "User",

	APPLICATION_LOCALE: "en_US",

	NO_LIMIT: 0,

	CENTRAL_SERVER: "Central Server"
};
